[package]
name = 'zoomerkernel'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'zoomerkernel'

[dependencies]
extendr-api = {version ="0.3.1", features =["ndarray"]}
indicatif = {version = "*", features = ["rayon"]}
rand = "0.8.5"
rayon = "1.5.3"
