# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_zoomerkernel_wrappers", use_symbols = TRUE, package_name = "zoomerkernel")

#' @docType package
#' @usage NULL
#' @useDynLib zoomerkernel, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
rbf_kernel_matrix <- function(x_robj, bw) .Call(wrap__rbf_kernel_matrix, x_robj, bw)

#' calculate the random-pivot cholesky factorization
#' @export
rpchol <- function(x_robj, k, bw) .Call(wrap__rpchol, x_robj, k, bw)

#' Kernel Balance Statistic
#' @export
kbalstat <- function(x_robj, z, w, k, bw, nboots) .Call(wrap__kbalstat, x_robj, z, w, k, bw, nboots)

